# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    restart: always
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  postgres:
    driver: local